import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import {roboto_mono} from './components/fonts'
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: '900',
  subsets: ['latin'],
  display: 'swap',
})
   
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen bg-fixed background-image:https://www.pexels.com/photo/mountains-covered-with-snow-1785493/` }>
      <Navbar />
        {children}
      
      </body>
    </html>
  );
}

/*
<div
       className="bg-fixed"
       style ={{backgroundImage: "url('https://images.pexels.com/photos/1785493/pexels-photo-1785493.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')"}}>
</div>
*/ 
 